### ISSUE TITLE
Kdrama Section Not found

### ISSUE THREAD

**Issue by skgupta507** [real-zephex/Dramalama#1]
hello @real-zephex 
as mentioned in the readme this site also has Kdrama But i couldn`t find the option to search or watch any  can u clearify my concern.
and by the way its a very good website iam regurlarly using it o read manga.

**Comment by real-zephex** [comment]
Sorry for the inconvenience @skgupta507 
I am currently rewriting the kdrama page. I just got over with my exams and I will complete it within few days. 
_Thank you for the kind words though_

**Comment by real-zephex** [comment]
![image](https://github.com/real-zephex/Dramalama/assets/143923795/294669ca-f831-4172-933c-60e703c90348)
