### ISSUE TITLE
Pop up player doesnt work for anime on newest commit

### ISSUE THREAD

**Issue by dillfrescott** [real-zephex/Dramalama#12]
:(

**Comment by zephex-alt** [comment]
Looking into this right now. I can't seem to re-create this issue in dev environment.

**Comment by real-zephex** [comment]
have you tried the netlify instsance?
https://dramalama.netlify.app

Can you please try visiting the same anime on the above url and report the behaviour?

**Comment by dillfrescott** [comment]
I'm so sorry I think I know what it is. I do a quick search and replace on my fork because I use my own selfhosted consumet. Something must have gone sour when it tried to merge your commits with mine on my instance

**Comment by real-zephex** [comment]
Check now

**Comment by dillfrescott** [comment]
Okay. I'm out and about right now using the github app, so when I get back to my desktop machine I'll be able to try it. 

I'll report back later

**Comment by dillfrescott** [comment]
Hmmm was there an update to the code? The pop up player still isnt showing up on my fork.

[these](https://github.com/real-zephex/Dramalama/compare/master...dillfrescott:Dramalama:master) are the only changes I made...

**Comment by real-zephex** [comment]
Have you tried syncing up your fork with mine?

**Comment by dillfrescott** [comment]
Yes! Its working well on netlify! But when I go to my fork, it says its not behind any commits.

**Comment by real-zephex** [comment]
@dillfrescott 
It should be fixed now. Sync up you repo to mine and test it again.

**Comment by dillfrescott** [comment]
Okay

**Comment by dillfrescott** [comment]
Indeed, it has been fixed! Thank you so much!!!!
