### ISSUE TITLE
Ads in movie section even with adblockers on.

### ISSUE THREAD

**Issue by dillfrescott** [real-zephex/Dramalama#23]
![Screenshot_20240508_093618](https://github.com/real-zephex/Dramalama/assets/56714680/08131ddf-2944-42b8-b63e-581ba1da0aef)

I think it manages to place itself inside the player frame so it somehow avoids the browser adblock...

**Comment by real-zephex** [comment]
> ![Screenshot_20240508_093618](https://private-user-images.githubusercontent.com/56714680/328908856-08131ddf-2944-42b8-b63e-581ba1da0aef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDEzMjgsIm5iZiI6MTcxNTI0MTAyOCwicGF0aCI6Ii81NjcxNDY4MC8zMjg5MDg4NTYtMDgxMzFkZGYtMjk0NC00MmI4LWI2M2UtNTgxYmExZGEwYWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA3NTAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNzRiZGVlZDI2OGUzODYxYzQ2NGE4MmYxMTBlNGE0ZDc1ZWUzNjg5MDE0Y2Q5ODgyODJjYjQ0YjI2NWFiYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t2lWFNVG9gV__pKhVXwdR1N_mcDv12gi_pdhaFn6Za4)
> 
> I think it manages to place itself inside the player frame so it somehow avoids the browser adblock...

Well, that's unfortunate. 
By the way, what adblocker are you using? 
_If you are using uBlock Origin, then you can enable more block lists in the extension's settings_

Afaik, `vidsrc.icu` and Server 2 on `autoembed.cc` are ad-free.

**Comment by dillfrescott** [comment]
Brave shields.

**Comment by dillfrescott** [comment]
> Afaik, vidsrc.icu and Server 2 on autoembed.cc are ad-free.

ok noted! Maybe you should group the servers into "need an ad blocker" and "dont need one"

**Comment by dillfrescott** [comment]
This is an unrelated question, but do you know an easy way to export the build to be able to be hosted statically? I tried next export and it was throwing some errors.

**Comment by real-zephex** [comment]
if you want to run this project locally, clon
