### ISSUE TITLE
watchpage/player fix required

### ISSUE THREAD

**Issue by skgupta507** [real-zephex/Dramalama#30]
hey @real-zephex iam writing this issue regarding the player scroll bar which is showing during play back. i have added the screenshot of it below.
so as u can see in the image below the player  shows a scroll bar which is looking ugly conpared to the whole sites UI. so can u fix that for us.
![Capturem](https://github.com/real-zephex/Dramalama/assets/131786207/1a339c4f-34c9-4ed8-9ef9-2255624b5714)

**Comment by real-zephex** [comment]
Hey @skgupta507 
Thank you for bringing it to my attention. I will look into it soon.

**Comment by real-zephex** [comment]
@skgupta507 
Can you please confirm whether it's fixed or not?

**Comment by skgupta507** [comment]
> @skgupta507 Can you please confirm whether it's fixed or not?

hi @real-zephex yes its fixed.
thank you for fixing it so soon.

**Comment by real-zephex** [comment]
> > @skgupta507 Can you please confirm whether it's fixed or not?
> 
> hi @real-zephex yes its fixed.
> thank you for fixing it so soon.

_Well, I am glad that someone is using my website. So, I thought I better fix it._

Anyways, closing this issue now.
