### ISSUE TITLE
[suggestions] Footer update UI/Design

### ISSUE THREAD

**Issue by skgupta507** [real-zephex/Dramalama#31]
Hey @real-zephex i have a suggestion for the footer design as of now the footer is normal which is very simple with only the creator credits.
but how about redesigning it and add some more components to it like _**DMCA, Privacy policy, terms of service, year of creation and links to ur social and GitHub profile**_  
if u  like my suggestion let me know.

**Comment by real-zephex** [comment]
Sorry for the late response.
Currently, I am in the middle of updating the UI for all the pages. I will look into re-designing the footer once I am done with the prior tasks.
_Thank you for the suggestion though_
