### ISSUE TITLE
Option to download stream

### ISSUE THREAD

**Issue by flawsom** [real-zephex/Dramalama#48]
it wuld be really great to have an option to download the episode/video/stream from the each of the respective sections 

1. [Anime](https://dramalama-nine.vercel.app/anime)
2. [K-Dramas](https://dramalama-nine.vercel.app/kdrama)
3. [Manga](https://dramalama-nine.vercel.app/manga)
4. [TV shows](https://dramalama-nine.vercel.app/web-series)
5. [Movies](https://dramalama-nine.vercel.app/movies)

**Comment by real-zephex** [comment]
And also, movies already have a download option

**Comment by real-zephex** [comment]
As for mangas, I am working on a download system, but I can't state an ETA.

**Comment by real-zephex** [comment]
[MANGA DOWNLOAD](https://github.com/real-zephex/Dramalama/commit/8335a9661f8f553b5e8d894fb2e167184eca09bb)

Added direct downloads for mangas

**Comment by flawsom** [comment]
@real-zephex  Wouldn't making a new fetch function from anilist or consumet and add it to a new button component just work for the anime downloads ?

**Comment by real-zephex** [comment]
> @real-zephex  Wouldn't making a new fetch function from anilist or consumet and add it to a new button component just work for the anime downloads ?

What does that even mean?
