### ISSUE TITLE
Some popular manga titles not showing any chapters

### ISSUE THREAD

**Issue by dillfrescott** [real-zephex/Dramalama#7]
Hello! Love this project! But I noticed that some popular manga titles arent showing any content. Not sure if this is a glitch or what. But thought I'd bring it up to you so you can work on it.

![Screenshot_20240429_204354](https://github.com/real-zephex/Dramalama/assets/56714680/efa9a155-c84a-4a8a-ac7d-d6bbecb09cfe)

**Comment by dillfrescott** [comment]
Could this be just that Consumet cant find any chapters?

**Comment by dillfrescott** [comment]
Also one last thing. It seems with kdramas, the video player slides out at the bottom, and with anime, it is a popup. Not a big deal but the inconsistency triggers my OCD lol

**Comment by zephex-alt** [comment]
> Also one last thing. It seems with kdramas, the video player slides out at the bottom, and with anime, it is a popup. Not a big deal but the inconsistency triggers my OCD lol

Sorry about that, I will fix it soon.

**Comment by zephex-alt** [comment]
> Could this be just that Consumet cant find any chapters?

![image](https://github.com/real-zephex/Dramalama/assets/166333351/d666ab89-138d-420d-bfb2-fcc8867bad10)
Seems like the chapters have 0 pages, that's why no chapters are being displayed there.

**Comment by dillfrescott** [comment]
Oh, interesting

**Comment by zephex-alt** [comment]
> Oh, interesting

![image](https://github.com/real-zephex/Dramalama/assets/166333351/2f0c5b18-aecd-4d8c-883c-e1952b45eeb7)

**Comment by real-zephex** [comment]
The video players have been fixed.
