### ISSUE TITLE
SITE WAS CHANGED ? U DIDN'T HAVE TO GO THIS HARD

### ISSUE THREAD

**Issue by papi028** [real-zephex/Dramalama#77]
can we get the code?

**Comment by harshascode** [comment]
Yes bro,

**Comment by real-zephex** [comment]
I will soon make it public. There are a lot of things that I need to add and fix right now!
_sorry for the late response though_

**Comment by papi028** [comment]
Alright

**Comment by dillfrescott** [comment]
@real-zephex I would love to attempt to run the new version locally on my machine. Hows the code release coming along?

**Comment by real-zephex** [comment]
Checkout the main branch!
