### ISSUE TITLE
Would you ever consider adding a non anime movies section?

### ISSUE THREAD

**Issue by dillfrescott** [real-zephex/Dramalama#9]
I noticed consumet indexes non-anime and korean drama content as well, such as american or european shows and movies.

Not sure if youd like to add it but i think a relevent section on the home page would be sweet. Ive been looking for an all in one, streaming site to self host, and most on github only do non anime or anime content, rarely both.

**Comment by real-zephex** [comment]
To my knowledge, Flix HQ was the sole source for movies and TV shows on Consumet. However, Flix HQ's team has altered the encryption method, and it was mentioned on the Discord server that Consumet will no longer support Flix HQ. 

This does not imply that adding movies and TV shows support is impossible. Other sources exist, such as VidSrc Pro, among others, which unfortunately come with a significant number of ads. This is manageable for users with ad blockers, but for those unaware of such tools, the ads and redirects can be a source of frustration.

Anyways, I will try looking for some good sources. I am not sure whether I will find them or not so I can't promise anything at this moment.

(I will close this issue for now)

**Comment by dillfrescott** [comment]
Okay!
